### ISSUE TITLE
Crash with Server Utilities with Server Teams without a Player

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/GTNH-Web-Map#15]
### Your GTNH Discord Username

StoneLegion

### Mod Version

gtnh-web-map-0.3.32.jar

### Bug Report

As far as I know reading this error is based on me having teams without a player. This is actually a feature:
/team create_server_team test

Maybe might want to offer a option to highlight/hide server teams as well if it's easy on Dynmap. We use it for Spawn and our Railway system.

Hope this is enough info :)

```
java.lang.NullPointerException: Cannot invoke "serverutils.lib.data.ForgePlayer.getName()" because "team.owner" is null
	at Launch//org.dynmap.forge.integration.ServerUtilitiesClaimedChunksMarkers.update(ServerUtilitiesClaimedChunksMarkers.java:90)
	at Launch//org.dynmap.forge.integration.ServerUtilitiesClaimedChunksMarkers.doUpdates(ServerUtilitiesClaimedChunksMarkers.java:124)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1588_ServerUtilitiesClaimedChunksMarkers_doUpdates_ServerTickEvent.invoke(.dynamic)
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at Launch//cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Java Version

Java 8

### Mod List or GTNH Pack Version

2.7.0 RC1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by dvdmandt** [comment]
This should be fixed in 0.3.33.
